workflows:
  android-app:
    name: Android App Build
    # حذف قسم repository لأنه غير مسموح به في Codemagic
    instance_type: mac_mini_m1
    environment:
      # نعلّق على توقيع الـ keystore لأنه غير متوفر حاليًا
      # android_signing:
      #   - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.thankyouapp"
        GOOGLE_PLAY_TRACK: internal
    scripts:
      - name: التحقق من هيكل المجلدات
        script: |
          echo "التحقق من هيكل المشروع..."
          pwd
          find . -maxdepth 3 -type d
          ls -la
          
      - name: تجهيز أذونات ملفات Gradle
        script: |
          echo "منح صلاحيات التنفيذ لملف gradlew..."
          chmod +x ./gradlew
          
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
        
      - name: إعداد بيئة البناء بدون توقيع
        script: |
          echo "بناء التطبيق بدون توقيع..."
          
      - name: Build Android app (without signing)
        script: |
          echo "بدء عملية بناء التطبيق..."
          ./gradlew assembleRelease --stacktrace
          
      - name: Run tests
        script: |
          echo "تشغيل الاختبارات..."
          ./gradlew test --stacktrace
          
      - name: Build debug APK (without signing)
        script: |
          echo "بناء نسخة التصحيح (debug)..."
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/bundle/release/app-release.aab
      - app/build/reports/tests/test-report.txt
      - app/build/reports
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
      # نعلق على نشر Google Play لأننا نحتاج إلى بيانات اعتماد
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: $GOOGLE_PLAY_TRACK
      #   submit_as_draft: true
